### ISSUE TITLE
哥们，您的编辑器很简洁实用

### ISSUE THREAD

**Issue by cynhard** [baixuexiyang/artEditor#1]
哥们，您的编辑器很简洁实用，现在有个问题是，怎么随着form表单提交呢？

**Comment by siliushi** [comment]
提交表单之前用getValue获取内容，然后放到form里的隐藏域，比如：
$('.submit').on('click', function(e) {
    e.preventDefault();
    $('.hidden').val($('.artEditor').getValue());
    $(this).submit();
});
后面会考虑加上同步提交的

**Comment by cynhard** [comment]
已经搞定了，谢谢

**Comment by siliushi** [comment]
新增配置参数formInputId，该参数表示form隐藏域的id
