### ISSUE TITLE
请问，如果想删除已经上传的图片，怎么删除

### ISSUE THREAD

**Issue by xuehf** [baixuexiyang/artEditor#10]
如题

**Comment by siliushi** [comment]
1、如果编辑器中回显的图片是从本地读取的，直接delete文本框中的图片就可以实现
2、如果回显的图片是从服务端读取的，服务端可以不处理，提交内容里不包含图片就可以

**Comment by xuehf** [comment]
(图片是从服务器返回的)
可是服务器上有关联的表，列表页面显示前3张图片会把已经删除的显示出来

**Comment by siliushi** [comment]
列表页面显示前3张图片会把已经删除的显示出来     这个我有些不明白，难道你的展示不是编辑器里的内容？如果编辑器里的图片删掉了，对应的展示也会删掉呀

**Comment by xuehf** [comment]
我们的数据库设计是：有一个专门的附件表，上传后会关联文章id，我们详情页面用的编辑器里面的内容，列表页面因为设计的只展示第一张图并且是在文字下面（app布局原因），所以就根据文章id取得数据库的第一张图片名称，然后把编辑器的<img>标签屏蔽了。

**Comment by siliushi** [comment]
这种情况没有遇到过，因为这个是编辑器用户可以通过删除键来删除图片，所以需要单独监听删除，然后通知服务端

**Comment by siliushi** [comment]
图片上传之后先不要传到服务端，等提交文本内容的时候在分别提交内容和图片，这样应该能解决你的问题
