### ISSUE TITLE
为什么我在手机上插入点时候，每次插入图片都会插入在最顶部

### ISSUE THREAD

**Issue by zhujp** [baixuexiyang/artEditor#12]
为什么我在手机上插入点时候，每次插入图片都会插入在最顶部

**Comment by sunnynings** [comment]
是因为你失去焦点以后，默认会加在最顶部。 @zhujp

**Comment by xuehf** [comment]
那焦点怎么获取，必须长按吗？知乎手机客户端的是点击一次就定位到了

**Comment by xuehf** [comment]
@sunnyning @baixuexiyang

**Comment by shi1991** [comment]
推荐使用Caret.js【https://github.com/ichord/Caret.js】，这个组件来获取和设置光标在div中的位置。在添加图片前获取光标位置，在图片上传成功后设置光标位置。

**Comment by siliushi** [comment]
@zhujp @sunnynings @xuehf @shi1991 已经解决

**Comment by shi1991** [comment]
@baixuexiyang 作者怎么解决的？

**Comment by siliushi** [comment]
@shi1991 失去焦点记住光标位置
