### ISSUE TITLE
移动端图片无法删除问题

### ISSUE THREAD

**Issue by Gii16** [baixuexiyang/artEditor#15]
你好！
请问该编辑器用于部分安卓系统时，出现图片无法删除（编辑时）的情况应该如何处理？
即，光标在图片后面，点击删除键，光标直接跳过图片，删除了图片前面的文字

**Comment by siliushi** [comment]
是不是图片设置display了？

**Comment by Gii16** [comment]
没有设置display，我使用部分安卓手机的浏览器直接打开您提供的demo，也会存在图片无法删除的问题

**Comment by siliushi** [comment]
@Gii16 用最新代码在测试下，如果有问题请把机型和浏览器提供下
