### ISSUE TITLE
请问怎样对图片压缩后再上传呢

### ISSUE THREAD

**Issue by paulyu12** [baixuexiyang/artEditor#20]
1. 请问上传的时候只能是整个html内容一起post到服务器端吗？
2. 我在另一个页面加载整个html时，有时候会因为图片没加载出来导致图片下面的html都无法加载。我想讲图片数据压缩下，请问能做到么，怎么做，谢谢

**Comment by siliushi** [comment]
第一个问题图片可以单独上传，第二个问题设置showServer为true就可以将图片上传到服务器然后回显

**Comment by paulyu12** [comment]
非常感谢！我对jquery了解的不多，如果您方便的话，能否详细说下图片单独上传应该如何做？

**Comment by siliushi** [comment]
$('#content').artEditor({
        imgTar: '#imageUpload',
        limitSize: 5,
        showServer: true,  // 这里设置成true
        uploadUrl: 'http://www.artEditor.com/upload',  // 上传的路径
        data: {},
        uploadField: 'image',
        placeholader: '<p>请输入文章正文内容</p>',
        validHtml: ["<br/>"],
        formInputId: 'target',
        uploadSuccess: function(res) {
            // 这里return从服务端返回来的图片地址
            return res.path;
        },
        uploadError: function(res) {
            // something error
            console.log(res);
        }
    });

**Comment by paulyu12** [comment]
谢谢
