### ISSUE TITLE
这种编辑器还有类似开源的吗？

### ISSUE THREAD

**Issue by waittingbar** [baixuexiyang/artEditor#22]
我需要这种编辑器啊，需要和淘宝发布那个手机端的

**Comment by siliushi** [comment]
应该有的，github上搜搜看

**Comment by waittingbar** [comment]
这个提问里面不能上传图片啊，我把你这改进了一下，但是还是有点问题，就是你的那个每次添加一张图片，显示的时候位置是怎么定的，我觉得应该默认是在最后面添加，或者鼠标在哪里就在哪里添加，现在每次添加都是最上面了

**Comment by siliushi** [comment]
你是不是点击上传图片的时候又点击了其他地方？只有点击form元素才能记住鼠标位置，后面会优化的，你可以给输入框加个失去焦点事件，然后记住鼠标的位置，上传完图片在把图片insert进去

**Comment by echosoar** [comment]
Medit https://medit.js.org
