### ISSUE TITLE
获取信息的完整代码，请指导！

### ISSUE THREAD

**Issue by lhk001** [baixuexiyang/artEditor#3]
`<script language="javascript">
$(document).ready(function(){
 $("form").submit(function(e){
$('#artEditor').val($('#content').getValue());
});
});
 </script>
<input type="hidden" name="content"  id="artEditor">`

我是用这个模式来获取的，不过就是图片上传以后都是无法打开，还请您指点下

**Comment by siliushi** [comment]
无法打开是不是无法显示的意思？
图片上传以后都是无法打开是什么情况下？是内容提交之后查看无法显示，还是上传图片之后就无法显示？
1、确定下你的showServer配置，如果是true，图片是从服务器上读取，看下图片的路劲是不是正确
2、如果是false，图片是读取本地文件，上传完图片之后肯定可以显示，内容提交之后查看无法显示，你看下内容提交之后图片的base64编码一样吗？如果不一样且数据是存在数据库的话，有可能是字段长度超过数据库最大长度。那就改用从服务器上读取

**Comment by lhk001** [comment]
感谢您的回复，我后来排查了下，这个是我服务器的问题，不是您编辑器的事，我服务器过滤了关键词才导致这个问题。最后，十分感谢您的编辑器，在手机上很好用
