### ISSUE TITLE
自动增加div-2

### ISSUE THREAD

**Issue by gjiefl** [baixuexiyang/artEditor#34]
非常感谢解决此问题
但还有个小问题
例如
1
2
3
4
5
如果在2 后面按回车 2和3 之间会空一行 能否把光标定在2和3 之间的空行上？

**Comment by siliushi** [comment]
这个问题我知道，如果不加一行空行，在2和3之间输入内容会清掉这个换行，这是因为浏览器在br换行输入内容会把当前br清掉

**Comment by siliushi** [comment]
后面会考虑加标记处理
