### ISSUE TITLE
点击编辑框外面， 然后再点击编辑框里面的图片会报错， 不过没什么影响

### ISSUE THREAD

**Issue by qiangguoguo** [baixuexiyang/artEditor#39]
点击编辑框外面， 然后再点击编辑框里面的图片会报错， 不过没什么影响

index.js:68 Uncaught DOMException: Failed to execute 'getRangeAt' on 'Selection': 0 is not a valid index.

传不鸟图片

**Comment by siliushi** [comment]
图片是可以传的
