### ISSUE TITLE
你好,我压缩图片之后 第一次上传后台接收到的为空,第二次才能接收到,请问为什么?

### ISSUE THREAD

**Issue by caijiajun** [baixuexiyang/artEditor#42]
![image](https://user-images.githubusercontent.com/26128463/28701804-3c291eda-738b-11e7-96ae-823e4b1cb59e.png)
![Uploading image.png…]()

index.js:143 kong
index.js:149 Object {images: "data:,"}
index.js:23 上传失败
index.js:25 123
index.js:151 false
index.js:156 地址为空啊!大兄弟 false
index.js:149 Object {images: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD…SgBc0ZptO7UAGaTNFJQAuaM0lFIBc0CkooAdWvWOK2KAP/9k="}
index.js:23 /upload/6092cdf4-3eb4-442e-9ffe-f682ef4149d2.jpg
index.js:151 http://192.168.0.9//upload/6092cdf4-3eb4-442e-9ffe-f682ef4149d2.jpg

**Comment by siliushi** [comment]
看看你的代码

**Comment by caijiajun** [comment]
![image](https://user-images.githubusercontent.com/26128463/28704453-35202a22-739d-11e7-8dba-d18d1ad3a951.png)
这里我把上传放到压缩图片后面了~后台能获取了~ 还想请问下,压缩图片的比例可以自行设置吗?

**Comment by caijiajun** [comment]
[artEditor.zip](https://github.com/baixuexiyang/artEditor/files/1182136/artEditor.zip)

**Comment by siliushi** [comment]
代码不对，看下文件里面的例子
$('#content').artEditor({
        imgTar: '#imageUpload',
        limitSize: 5,   // 兆
        showServer: false,
        uploadUrl: 'http://localhost/PROJECT_OWN/NodeJS/artEditor/service/service.php',
        data: {},
        uploadField: 'image',
        breaks: false,
        placeholader: '请输入文章正文内容',
        validHtml: ["<br/>"],
        formInputId: 'target',
        uploadSuccess: function (res) {
            // 这里是处理返回数据业务逻辑的地方
            // `res`为服务器返回`status==200`的`response`
            // 如果这里`return <path>`将会以`<img src='path'>`的形式插入到页面
            // 如果发现`res`不符合业务逻辑
            // 比如后台告诉你这张图片不对劲
            // 麻烦返回 `false`
            // 当然如果`showServer==false`
            // 无所谓咯
            var result = JSON.parse(res)
            if (result['code'] == '100') {
                return result['data']['url'];
            } else {
                switch (result['code']) {
                    case '101': {
                        alert('图片太大之类的')
                    }
                }
            }
            return false;
        },
        uploadError: function (status, error) {
            //这里做上传失败的操作
            //也就是http返回码非200的时候
            alert('网络异常' + status)
        }
    });

**Comment by siliushi** [comment]
压缩比例目前没有配置

**Comment by caijiajun** [comment]
好的~谢谢~
