### ISSUE TITLE
chrome上粘贴控制台报错

### ISSUE THREAD

**Issue by stanye** [baixuexiyang/artEditor#44]
![image](https://user-images.githubusercontent.com/10014869/29115896-c4e8901c-7d2b-11e7-9432-c567f62b822b.png)
![image](https://user-images.githubusercontent.com/10014869/29115912-ce33d7f8-7d2b-11e7-8689-4a1abf410985.png)

使用姿势不对吗？

**Comment by siliushi** [comment]
https://github.com/baixuexiyang/clipBoard.js
这里面有粘贴的处理
