### ISSUE TITLE
提供的压缩处理怎么实现

### ISSUE THREAD

**Issue by nicholasMI** [baixuexiyang/artEditor#46]
我看源码里面有压缩的处理 可以配置的参数部分没有这一块 要怎么使用?

**Comment by siliushi** [comment]
先设置图片大小超过多少会被压缩（compressSize），如果上传的图片超过这个大小会自动压缩，我测试了下压缩比是不准确的，所以没有提供压缩比
https://github.com/baixuexiyang/artEditor/wiki/html5%E5%9B%BE%E7%89%87%E5%8E%8B%E7%BC%A9
