### ISSUE TITLE
光标定位问题？

### ISSUE THREAD

**Issue by gaohuasheng** [baixuexiyang/artEditor#53]
我在移动端使用该编辑器的时候，发现光标随点击文字位置无法定位，总是定位到文字末尾。请问这个是怎么解决的。

**Comment by siliushi** [comment]
测试了下没有这个问题，麻烦提供下运行环境

**Comment by wufanldxl** [comment]
这个问题好像是富文本在移动端的通病，并不是必现的样子

**Comment by siliushi** [comment]
@wufanldxl 我这边没出现过一次，能提供下测试的环境吗？
