### ISSUE TITLE
关于移动富文本编辑器图片上传的疑问

### ISSUE THREAD

**Issue by cuizhecode** [baixuexiyang/artEditor#54]
图片上传发送的请求数据是base64，发送前应该转化为blob的对象吧，要不然太大了无法传输到后台是吗？我碰到了这个问题

**Comment by pool611** [comment]
post方式的话应该对参数几乎没有大小限制吧，当然图片超过几兆后最好还是压缩一下

**Comment by cuizhecode** [comment]
不行  我试了base64太长了传不过去，后台是java。通过把base64转blob对象可以传过去，不知道是不是我哪里弄错了。

**Comment by pool611** [comment]
服务器端是否有post接收最大值限制，比如tomcat的配置文件里maxPostSize="0"表示无限制，tomcat默认是2M的限制大小

**Comment by cuizhecode** [comment]
对的，是这样的，我查清原因了不是传不过去，是传过去以后数据库放不下base64

**Comment by siliushi** [comment]
最好放在图片服务器上，数据库只需要存文件地址
