### ISSUE TITLE
引入此插件，但是在魅蓝的手机上面上传图片之后，然后用键盘的删除键删除不掉图片能删除文字

### ISSUE THREAD

**Issue by sucuiping** [baixuexiyang/artEditor#65]
引入此插件，但是在魅蓝的手机上面上传图片之后，然后用键盘的删除键删除不掉图片能删除文字，群主知道是什么原因吗？

**Comment by siliushi** [comment]
改下图片的display属性

**Comment by sucuiping** [comment]
我修改了图片的display属性还是不行哦，请问修改成什么模式，这个默认是block模式，然后我修改为inline-block和inline模式都不行哦。
