### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by wsmeichao** [baixuexiyang/artEditor#8]
1:当在编辑范围内失去焦点时，插入图片总是默认插入到首部去(移动端聚焦在可编辑范围时会弹出软键盘，会把上传图片按钮弹出可视范围->这个是个人的场景)，能否追踪到失去光标的位置，然后插入到上次光标的位置

**Comment by siliushi** [comment]
demo页面是没有这个问题的，http://baixuexiyang.github.io/artEditor/
插入图片总是默认插入到首部去有可能是因为点击的那个元素不是form元素，demo页面是一个input type="file"元素，麻烦把代码贴下

**Comment by wsmeichao** [comment]
经过检测，确实会出现如此的问题，举个栗子，一开始的时候输入一大堆的文字，然后鼠标点击其他位置(使其失去焦点)，然后直接点插入图片，它会自动插到顶部去->(demo上测试也会出现这样的问题)

**Comment by siliushi** [comment]
这种就情况就不用考虑了，如果要实现，那就在失去焦点的时候取到焦点位置保存起来

**Comment by wsmeichao** [comment]
有一个比较头疼的问题是：用户如果点击了其他部位，我可以判定是blur，但是用户如果点软键盘的完成按钮，我该怎么去捕捉这个事件？

**Comment by siliushi** [comment]
建议这种情况不用处理，因为是在手机端，不会出现pc浏览器上鼠标点击的问题。手机上用户的操作都是明确的

**Comment by wsmeichao** [comment]
好的，thx
