### ISSUE TITLE
能否获得选者图片的file，这里用jsp服务端无法上传图片

### ISSUE THREAD

**Issue by 287138531** [baixuexiyang/artEditor#9]
{"message":"请选择文件。","error":1}

服务端 利用的是kindeditor那种上传方式。。。。

请问服务端应该怎么处理？

**Comment by siliushi** [comment]
图片上传有两种，1、上传服务返回链接显示，2、读取本地文件显示，最终和文章内容一起保存到服务端
确认提交是采用的异步还是form提交？
服务端就像普通的提交处理就行

**Comment by 287138531** [comment]
这里我还要 吧图片压缩再上传  
  利用这个 var xhr = new XMLHttpRequest();   吧files上传
我可以改代码。。。但是不太懂。。我要怎么拿到这个input  file 的 id 
利用这个id我加压缩代码再上传

你的是转成base64再上传的。。。。可是太大了。。
You must initialize the xml-security library correctly before you use it. Call the static method "com.sun.org.apache.xml.internal.security.Init.init();" to do that before you use any functionality from that library.

**Comment by 287138531** [comment]
可以给个qq或者邮箱吗？

**Comment by siliushi** [comment]
个人信息有我的邮箱
